version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - .:/app
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}

    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    # Other configurations for 'nginx'

  db:
#    container_name: data-engineering_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
