version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map Django port to host
    environment:
      - APP_INSTANCE=app

  nginx:
    image: nginx:latest
#    networks:
#      - myapp_network
    ports:
      - "8001:8001"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /home/tk-lpt-395/certs:/etc/nginx/certs
    depends_on:
      - app


#    volumes:
#      - /home/tk-lpt-395/Documents/TUTORIAL/CICD/Sample APP/recipe-app-api-devops-starting-code/app/media:/app/media




