name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx:latest
        ports:
          - 8001:8001

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build the Docker image
      run: docker build . --file Dockerfile

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Run migrations
      run: docker-compose exec app python manage.py migrate

    # Add additional steps for other commands you might want to run (e.g., running tests)
