version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    # Other configurations for 'app'

  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    # Other configurations for 'nginx'

