name: Quality Assurance

on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.3.2

      - name: Install Dependencies
        run: poetry install && poetry run pre-commit install

      - name: Lint
        run: poetry run make lint  # Replace with the linting command for your project
