# Step 1: Define the name of the workflow and specify when it should trigger
name: Django CI/CD

on:
  push:
    branches:
      - main

# Step 2: Create a job (e.g., "build") that runs on a specific virtual environment
jobs:
  build:
    runs-on: ubuntu-latest

    # Step 3: Use an action to check out the repository's code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 4: Use an action to set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 5: Run commands to install Python dependencies (e.g., using pip)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 7: Build and Run Docker Container
      - name: Build and Run Docker Container
        run: |
          docker-compose up -d
