name: Merge to Main

on:
  push:
    branches:
      - action-flows

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "saqibmehmood199@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Merge to main
        run: |
          git checkout main
          git merge ${{ github.sha }}
          git push origin main
