name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: apt-get update && apt-get install -y make

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
          # Any other installation commands you might have

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Setup Pre-commit Hooks
        run: pre-commit install

      - name: Lint
        run: make lint  # Assuming you have a lint target in your Makefile

      - name: Test
        run: make test  # Assuming you have a test target in your Makefile
