name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.8-slim

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: apt-get update && apt-get install -y make

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2

      - name: Install Dependencies
        run: |
          make install
          make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
